config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'static_pages/home' => 'static_pages#home'
  get 'static_pages/paginate' => 'static_pages#paginate'
  root  'static_pages#home'

  resource :dropzone_files, only: [:create, :destroy]

  post 'tinymce/create' => 'tinymce#create', as: :tinymce_create

  resources :videos, only: [:create]
  resources :votes, only: [:create]

end

app/views/skills/_carrierWave.html.haml
%h1
  CarrierWave

app/views/skills/_devise.html.haml
- if user_signed_in?

  You email:
  = current_user.email

  = link_to('LogOut', destroy_user_session_path, :remote => true)

- else
  = render 'skills/devise/sign_in', resource: resource

app/views/skills/_deviseOmniauth.html.haml
- pages = {myfiles: 0, top: 0, new: 0} if pages.nil?

.col-md-6
  .jumbotron.skill_info.devise-omniauth
    Devise is a flexible authentication solution for Rails based on Warden. It:
    %ul
      %li Is Rack based;
      %li Is a complete MVC solution based on Rails engines;
      %li Allows you to have multiple models signed in at the same time;
      %li Is based on a modularity concept: use only what you really need.

    It's composed of 10 modules:
    %ul
      %li Database Authenticatable: hashes and stores a password in the database to validate the authenticity of a user while signing in. The authentication can be done both through POST requests or HTTP Basic Authentication.
      %li Omniauthable: adds OmniAuth (https://github.com/intridea/omniauth) support.
      %li Confirmable: sends emails with confirmation instructions and verifies whether an account is already confirmed during sign in.
      %li Recoverable: resets the user password and sends reset instructions.
      %li Registerable: handles signing up users through a registration process, also allowing them to edit and destroy their account.
      %li Rememberable: manages generating and clearing a token for remembering the user from a saved cookie.
      %li Trackable: tracks sign in count, timestamps and IP address.
      %li Timeoutable: expires sessions that have not been active in a specified period of time.
      %li Validatable: provides validations of email and password. It's optional and can be customized, so you're able to define your own validations.
      %li Lockable: locks an account after a specified number of failed sign-in attempts. Can unlock via email or after a specified time period.

    OmniAuth is a library that standardizes multi-provider authentication for web applications. It was created to be
    powerful, flexible, and do as little as possible. Any developer can create strategies for OmniAuth that can
    authenticate users via disparate systems. OmniAuth strategies have been created for everything from Facebook to LDAP.
.col-md-6
  - if user_signed_in?
    = render 'users/devise/profile', resource: resource, pages: pages
  - else
    = render 'users/devise/sign_in', resource: resource, pages: pages

app/views/skills/_dropzone.html.haml
- puts "#{pages}".red
.col-md-5
  #image_show
.col-md-7
  %ul#nav-dropzone.nav.nav-tabs.nav-justified
    %li.dropzone_nav_add{:role => 'presentation'}
      %a{:href => '#firstPage/slide2', onClick: 'tabsDropzone("add")'} Add
    %li.dropzone_nav_myfiles{:role => 'presentation'}
      %a{:href => '#firstPage/slide2', onClick: 'tabsDropzone("myfiles")'} My files
    %li.dropzone_nav_top{:role => 'presentation'}
      %a{:href => '#firstPage/slide2', onClick: 'tabsDropzone("top")'} TOP
    %li.dropzone_nav_new{:role => 'presentation'}
      %a{:href => '#firstPage/slide2', onClick: 'tabsDropzone("new")'} New

  #media-contents
    #media_tabs
      #media_add
        - if user_signed_in?
          = form_tag '/dropzone_files', method: :post, class: 'dropzone drop_form', id: 'media-dropzone' do
            .fallback
              = file_field_tag 'media', multiple: true
        - else
          = render 'users/devise/sign_in', pages: pages
        #media_download
      #media_myfiles
        - if user_signed_in?
          = render 'dropzone_files/files', pages: pages, files: files_kaminari(pages, 'myfiles'), type_page: 'myfiles'
        - else
          = render 'users/devise/sign_in', pages: pages
      #media_top
        = render 'dropzone_files/files', pages: pages, files: files_kaminari(pages, 'top'), type_page: 'top'
      #media_new
        = render 'dropzone_files/files', pages: pages, files: files_kaminari(pages, 'new'), type_page: 'new'

app/views/skills/_googleMap.html.haml
.col-md-6
  #map
.col-md-6
  #warning Осталось: 8 точек
  #markers
  %label#range_val{:for => 'range'}
  %input#range{:max => '150', :min => '5', :type => 'range', :value => '80'}/
  #times
  %br/
  %input#checkbox{:type => 'checkbox'}/
  %label#checkbox_label{:for => 'checkbox'} Строить сразу
  .map-button{:onclick => 'buildRoutes()'} Build routes
  .map-button{:onclick => 'startDriving()'} Start drive!
  .map-button{:onclick => 'resetRoutes()'} Reset routes
  .map-button{:onclick => 'resetMarkers()'} Reset markers

app/views/skills/_tinymce.html.haml
.col-md-6
  = form_tag(tinymce_create_path, remote: true) do |f|
    = text_area_tag :content, '', :class => 'tinymce', :rows => 25, :cols => 120
    %br
    = submit_tag 'Send', class: 'btn btn-default'
.col-md-6
  #tinymce_messages
    = render 'tinymce/messages', messages: messages_tiny

app/views/skills/_youTube.html.haml
.col-md-6
  .jumbotron
    .container
      = form_for Video.new, remote: true do |f|
        .input-group
          = f.text_field :link, class: 'form-control youtube_link', :placeholder => 'Video link...'
          %span.input-group-btn
            = f.submit '+', class: 'btn btn-info'
  #youtube_player
.col-md-6
  #youtube_videos
    = render 'videos/all_video'