config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  get 'static_pages/home' => 'static_pages#home'
  get 'static_pages/paginate' => 'static_pages#paginate'
  root  'static_pages#home'

  resource :dropzone_files, only: [:create, :destroy]

  post 'tinymce/create' => 'tinymce#create', as: :tinymce_create

  resources :videos, only: [:create]
  resources :votes, only: [:create]

end

app/models/dropzone_file.rb
class DropzoneFile < ActiveRecord::Base
  mount_uploader :file, FileUploader

  belongs_to :user

  has_many :votes, dependent: :destroy

  def rate
    self.votes.sum(:like)
  end

end

app/controllers/dropzone_files_controller.rb
class DropzoneFilesController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    @media = current_user.dropzone_files.new(file: params[:file])
    if @media.save!
      respond_to do |format|
        format.json{ render :json => @media }
      end
    end
  end

  def destroy
    @file = DropzoneFile.find(params[:format]).destroy
    @pages = params[:pages]
    @type_page = params[:type_page]
  end

end

app/helpers/dropzone_files_helper.rb
module DropzoneFilesHelper
  def img(file)
    format = file.file_identifier.split('.').last
    %w(jpg jpeg png gif).any? {|f| f == format} ? true : false
  end

  def user_vote?(id)
    current_user.votes.where(dropzone_file_id: id).any?
  end

  def files_kaminari(pages, tab)
    pages = {myfiles: 0, top: 0, new: 0} if pages.nil?
    case tab
      when 'new'
        Kaminari.paginate_array(DropzoneFile.order('created_at DESC').in_groups_of(3)).page(pages[:new]).per(2)
      when 'top'
        hash = Hash.new
        DropzoneFile.all.each do |d|
          hash[d] = d.rate
        end
        Kaminari.paginate_array(hash.sort_by {|_key, value| value}.to_h.keys.reverse.in_groups_of(3)).page(pages[:top]).per(2)
      when 'myfiles'
        Kaminari.paginate_array(current_user.dropzone_files.order('created_at DESC').in_groups_of(3)).page(pages[:myfiles]).per(2)
      else
        puts 'und tab'.red
    end
  end

end

app/views/dropzone_files/_file.html.haml
- unless media.nil?
  .avatar_drpz
    = avatar media.user, '30x30' unless media.user.nil?
  .userinfo_drpz
    = media.user.email.split('@').first unless media.user.nil?
  %br
  - if img(media)
    = image_tag media.file.url, onClick: "showImage('#{media.file.url}')"
  - else
    = link_to image_tag('file.png', size: '150x150'), media.file.url, target: '_blank'

  - user_vote = user_vote? media.id if user_signed_in?
  = link_to '▲', votes_path(media.id, like: 1, pages: pages, type_page: type_page), method: :post, remote: true, class: 'like' if user_signed_in? && !user_vote
  = media.rate
  = link_to '▼', votes_path(media.id, like: -1, pages: pages, type_page: type_page), method: :post, remote: true, class: 'like' if user_signed_in? &&!user_vote

  = link_to 'test ▲', votes_path(media.id, like: 1, pages: pages, type_page: type_page), method: :post, remote: true, class: 'like' if user_signed_in?
  = link_to 'test ▼', votes_path(media.id, like: -1, pages: pages, type_page: type_page), method: :post, remote: true, class: 'like' if user_signed_in?

  = link_to 'x', dropzone_files_path(media.id, pages: pages, type_page: type_page), method: :delete, remote: true, class: 'pull-right delete' if media.user == current_user

app/views/dropzone_files/_files.html.haml
= paginate files,  :theme => 'twitter-bootstrap-3',
                    :pagination_class => 'pagination-sm',
                    :params => { :controller => '/static_pages', :action => 'paginate', type_page: type_page, pages: pages},
                     remote: true

- files.each do |group|
  .row
    - group.each do |media|
      - if media
        .col-md-4
          .thumbnail{id: "file_#{media.id}"}
            = render 'dropzone_files/file', media: media, pages: pages, type_page: type_page

app/views/dropzone_files/destroy.js.erb
$("#skill_dropzone").html("<%= escape_javascript(render('skills/dropzone', pages: @pages)) %>");
initDropzone();
tabsDropzone('<%= @type_page %>');